Module 2
avdhut1977/DevOps-Course-Starter pull request #4
Opened 2020-11-25 10:16 UTC by avdhut1977

Module 2 Project

2020-12-16 11:59 UTC, Jonesey13 requested changes
This is great but you're missing a few important requirements:

- Your `README.md` should explain how to add the trello credentials
- The project currently doesn't run as described as requests is missing (please run `poetry add requests`
- There is no class for todo tasks

2020-12-16 11:59 UTC, Jonesey13 commented on todo_app/app.py
> +    jsonResponse = requests.request("GET", url, params=queryparams).json()
In python variable names should be snake_case

2020-12-16 11:59 UTC, Jonesey13 commented on todo_app/app.py
> +    task = {'id': jsonResponse['id'], 'name': jsonResponse['name'], 'status_id': jsonResponse['idList'], 'board_id':jsonResponse['idBoard'] }
There should be a python class for handling task objects (with a constructor)

2020-12-25 17:44 UTC, avdhut1977 commented
Review changes have ben incorporated

2021-01-07 16:48 UTC, hugh-emerson approved these changes
You've addressed Alex's comments 👍 I've left some minor points but you can merge when you're ready.

2021-01-07 16:48 UTC, hugh-emerson commented on README.md
> +Trello Key and Token has been set in .env to use Trello APIs
You actually mean TRELLO_KEY and TRELLO_TOKEN.

Also you give no explanation for what they are.

More minor point - this shouldn't be inside the ` ```bash` section. You can preview what the document will look like in VSCode or you can see it when you view the repository in GitHub.

2021-01-07 16:48 UTC, hugh-emerson commented on pyproject.toml
> +pytest-cov = "^2.10.1"
These didn't need to be added yet

2021-01-08 14:04 UTC, merged